package client.print.topdown;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-15T20:40:58.100+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "PrintService-v2", 
                  wsdlLocation = "http://localhost:8080/osmanvlastic/PrintService-v2?wsdl",
                  targetNamespace = "http://www.printservice.org/") 
public class PrintServiceV2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.printservice.org/", "PrintService-v2");
    public final static QName TextPort = new QName("http://www.printservice.org/", "TextPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/osmanvlastic/PrintService-v2?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PrintServiceV2.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/osmanvlastic/PrintService-v2?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PrintServiceV2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PrintServiceV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrintServiceV2() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintServiceV2(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintServiceV2(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintServiceV2(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PrintService
     */
    @WebEndpoint(name = "TextPort")
    public PrintService getTextPort() {
        return super.getPort(TextPort, PrintService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrintService
     */
    @WebEndpoint(name = "TextPort")
    public PrintService getTextPort(WebServiceFeature... features) {
        return super.getPort(TextPort, PrintService.class, features);
    }

}
