
package client.print.topdown;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-16T22:24:59.873+01:00
 * Generated source version: 2.7.7
 * 
 */
public final class PrintServiceV2_TextPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.printservicev2.org/", "printServiceV2");

    private PrintServiceV2_TextPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PrintServiceV2_Service.WSDL_LOCATION;

      
        PrintServiceV2_Service ss = new PrintServiceV2_Service(wsdlURL, SERVICE_NAME);
        PrintServiceV2 port = ss.getTextPort();  
        
        {
        System.out.println("Invoking printReservation...");
        client.print.topdown.Reservation _printReservation_printReservation = new client.print.topdown.Reservation();
        java.lang.String _printReservation_email = "";
        try {
            port.printReservation(_printReservation_printReservation, _printReservation_email);

        } catch (PrintReservationFault e) { 
            System.out.println("Expected exception: PrintReservationFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
