
package client.print.topdown;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-15T21:48:39.741+01:00
 * Generated source version: 2.7.7
 * 
 */
public final class PrintServiceV2_TextPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.printservice.org/", "PrintServiceV2");

    private PrintServiceV2_TextPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PrintServiceV2_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PrintServiceV2_Service ss = new PrintServiceV2_Service(wsdlURL, SERVICE_NAME);
        PrintServiceV2 port = ss.getTextPort();  
        
        {
        System.out.println("Invoking printReservation...");
        client.print.topdown.Reservation _printReservation_printReservation = null;
        java.lang.String _printReservation_email = "";
        try {
            port.printReservation(_printReservation_printReservation, _printReservation_email);

        } catch (PrintReservationFault e) { 
            System.out.println("Expected exception: PrintReservationFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
