package server.print.topdown;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-17T09:48:29.021+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "printServiceV2", 
                  wsdlLocation = "classpath:top-down-PrintService.wsdl",
                  targetNamespace = "http://www.printservicev2.org/") 
public class PrintServiceV2_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.printservicev2.org/", "printServiceV2");
    public final static QName TextPort = new QName("http://www.printservicev2.org/", "TextPort");
    static {
        URL url = PrintServiceV2_Service.class.getClassLoader().getResource("top-down-PrintService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PrintServiceV2_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:top-down-PrintService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PrintServiceV2_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PrintServiceV2_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrintServiceV2_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintServiceV2_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintServiceV2_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintServiceV2_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PrintServiceV2
     */
    @WebEndpoint(name = "TextPort")
    public PrintServiceV2 getTextPort() {
        return super.getPort(TextPort, PrintServiceV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrintServiceV2
     */
    @WebEndpoint(name = "TextPort")
    public PrintServiceV2 getTextPort(WebServiceFeature... features) {
        return super.getPort(TextPort, PrintServiceV2.class, features);
    }

}
