
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package server.print.topdown;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-15T20:36:02.637+01:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "PrintService-v2",
                      portName = "TextPort",
                      targetNamespace = "http://www.printservice.org/",
                      wsdlLocation = "classpath:top-down-PrintService.wsdl",
                      endpointInterface = "server.print.topdown.PrintService")
                      
public class PrintServiceImpl implements PrintService {

    private static final Logger LOG = Logger.getLogger(PrintServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see server.print.topdown.PrintService#printReservation(server.print.topdown.Reservation  printReservation ,)java.lang.String  email )*
     */
    public void printReservation(Reservation printReservation,java.lang.String email) throws PrintReservationFault    { 
        LOG.info("Executing operation printReservation");
        System.out.println(printReservation);
        System.out.println(email);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PrintReservationFault("PrintReservationFault...");
    }

}
