
package server.print.topdown;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-17T09:48:28.904+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "PrintException", targetNamespace = "http://www.printservicev2.org/")
public class PrintException extends Exception {
    
    private server.print.topdown.PrintError printException;

    public PrintException() {
        super();
    }
    
    public PrintException(String message) {
        super(message);
    }
    
    public PrintException(String message, Throwable cause) {
        super(message, cause);
    }

    public PrintException(String message, server.print.topdown.PrintError printException) {
        super(message);
        this.printException = printException;
    }

    public PrintException(String message, server.print.topdown.PrintError printException, Throwable cause) {
        super(message, cause);
        this.printException = printException;
    }

    public server.print.topdown.PrintError getFaultInfo() {
        return this.printException;
    }
}
