
package server.print.topdown;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-15T21:46:10.498+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "PrintException", targetNamespace = "http://www.printservice.org/")
public class PrintReservationFault extends Exception {
    
    private server.print.topdown.PrintError printException;

    public PrintReservationFault() {
        super();
    }
    
    public PrintReservationFault(String message) {
        super(message);
    }
    
    public PrintReservationFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PrintReservationFault(String message, server.print.topdown.PrintError printException) {
        super(message);
        this.printException = printException;
    }

    public PrintReservationFault(String message, server.print.topdown.PrintError printException, Throwable cause) {
        super(message, cause);
        this.printException = printException;
    }

    public server.print.topdown.PrintError getFaultInfo() {
        return this.printException;
    }
}
