package client.print.bottomup;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-17T11:20:20.208+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "PrintService", 
                  wsdlLocation = "http://localhost:8000/PrintService?wsdl",
                  targetNamespace = "http://printservice.org/") 
public class PrintService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://printservice.org/", "PrintService");
    public final static QName TextPort = new QName("http://printservice.org/", "TextPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8000/PrintService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PrintService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8000/PrintService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PrintService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PrintService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrintService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PrintService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PrintService
     */
    @WebEndpoint(name = "TextPort")
    public PrintService getTextPort() {
        return super.getPort(TextPort, PrintService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrintService
     */
    @WebEndpoint(name = "TextPort")
    public PrintService getTextPort(WebServiceFeature... features) {
        return super.getPort(TextPort, PrintService.class, features);
    }

}
