
package client.print.bottomup;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.activation.DataHandler;
import javax.xml.namespace.QName;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.InputStream;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-17T11:20:19.997+01:00
 * Generated source version: 2.7.7
 */
public final class PrintService_TextPort_Client {

    private static final QName SERVICE_NAME = new QName("http://printservice.org/", "PrintService");

    private PrintService_TextPort_Client() {
    }

    public static InputStream getPrint() throws java.lang.Exception {
        URL wsdlURL = PrintService_Service.WSDL_LOCATION;

        PrintService_Service ss = new PrintService_Service(new URL("http://localhost:8080/osmanvlastic/PrintService?wsdl"), SERVICE_NAME);
        PrintService port = ss.getTextPort();

        InputStream is = null;
        System.out.println("Invoking printReservation...");
        client.print.bottomup.Reservation _printReservation_reservation = new client.print.bottomup.Reservation();
        _printReservation_reservation.setState(StateChoices.PAID);
        try {
            DataHandler _printReservation__return = port.printReservation(_printReservation_reservation);
            File temp;
            temp = File.createTempFile("reservation", ".txt");
            // Delete temp file when program exits.
            temp.deleteOnExit();

            //FileUtils.writeByteArrayToFile(temp, _printReservation__return);
            is = _printReservation__return.getInputStream();


        } catch (PrintException e) {
            System.out.println("Expected exception: PrintException has occurred.");
            System.out.println(e.toString());
        }

        return is;
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PrintService_Service.WSDL_LOCATION;

        PrintService_Service ss = new PrintService_Service(new URL("http://localhost:8080/osmanvlastic/PrintService?wsdl"), SERVICE_NAME);
        PrintService port = ss.getTextPort();

        {
            System.out.println("Invoking printReservation...");
            client.print.bottomup.Reservation _printReservation_reservation = new client.print.bottomup.Reservation();
            _printReservation_reservation.setState(StateChoices.PAID);
            try {
                DataHandler _printReservation__return = port.printReservation(_printReservation_reservation);
                File temp;
                temp = File.createTempFile("reservation", ".txt");
                // Delete temp file when program exits.
                temp.deleteOnExit();

                //FileUtils.writeByteArrayToFile(temp, _printReservation__return);
                InputStream is = _printReservation__return.getInputStream();
                System.out.println(is.toString());
                BufferedInputStream bin = new BufferedInputStream(is);
                int b;
                while ((b = bin.read()) != -1) {

                    char c = (char) b;

                    System.err.print("" + (char) b); //This prints out content that is unreadable.
                    //Isn't it supposed to print out html tag?
                }

            } catch (PrintException e) {
                System.out.println("Expected exception: PrintException has occurred.");
                System.out.println(e.toString());
            }
        }

        System.exit(0);
    }

}
