
package client.print.bottomup;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-17T11:20:20.164+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "PrintError", targetNamespace = "http://printservice.org/")
public class PrintException extends Exception {
    
    private client.print.bottomup.PrintError printError;

    public PrintException() {
        super();
    }
    
    public PrintException(String message) {
        super(message);
    }
    
    public PrintException(String message, Throwable cause) {
        super(message, cause);
    }

    public PrintException(String message, client.print.bottomup.PrintError printError) {
        super(message);
        this.printError = printError;
    }

    public PrintException(String message, client.print.bottomup.PrintError printError, Throwable cause) {
        super(message, cause);
        this.printError = printError;
    }

    public client.print.bottomup.PrintError getFaultInfo() {
        return this.printError;
    }
}
