package client.bank.secured;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-13T17:51:19.054+01:00
 * Generated source version: 2.7.7
 */
@WebServiceClient(name = "SecuredService",
        wsdlLocation = "http://aos.czacm.org/bank/secured?wsdl",
        targetNamespace = "http://centralbank.org/")
public class SecuredService extends Service
{

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://centralbank.org/", "SecuredService");

    public final static QName SecuredPort = new QName("http://centralbank.org/", "SecuredPort");

    static {
        URL url = null;
        try {
            url = new URL("http://aos.czacm.org/bank/secured?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SecuredService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://aos.czacm.org/bank/secured?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SecuredService(URL wsdlLocation)
    {
        super(wsdlLocation, SERVICE);
    }

    public SecuredService(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }

    public SecuredService()
    {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecuredService(WebServiceFeature... features)
    {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecuredService(URL wsdlLocation, WebServiceFeature... features)
    {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecuredService(URL wsdlLocation, QName serviceName, WebServiceFeature... features)
    {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns BankService
     */
    @WebEndpoint(name = "SecuredPort")
    public BankService getSecuredPort()
    {
        return super.getPort(SecuredPort, BankService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BankService
     */
    @WebEndpoint(name = "SecuredPort")
    public BankService getSecuredPort(WebServiceFeature... features)
    {
        return super.getPort(SecuredPort, BankService.class, features);
    }

}
