
package client.bank.secured;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-13T17:51:18.979+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "TransactionFault", targetNamespace = "http://centralbank.org/")
public class TransactionException extends Exception
{

    private client.bank.secured.TransactionFault transactionFault;

    public TransactionException()
    {
        super();
    }

    public TransactionException(String message)
    {
        super(message);
    }

    public TransactionException(String message, Throwable cause)
    {
        super(message, cause);
    }

    public TransactionException(String message, client.bank.secured.TransactionFault transactionFault)
    {
        super(message);
        this.transactionFault = transactionFault;
    }

    public TransactionException(String message, client.bank.secured.TransactionFault transactionFault, Throwable cause)
    {
        super(message, cause);
        this.transactionFault = transactionFault;
    }

    public client.bank.secured.TransactionFault getFaultInfo()
    {
        return this.transactionFault;
    }
}
